#####################################################################################################################################
#                                 项目 主要配置入口
#####################################################################################################################################

#设置端口以及项目名
server:
  port: 9001
  servlet:
    context-path: /quartz
    session:
      # session 到期时间
      timeout: 3600
#配置log4j2配置文件路径
logging:
  config: classpath:log4j2/log4j2.xml
#验证码配置文件
kaptcha:
  config: kaptcha/kaptcha.properties
#切环境 开发  测试  生产 dev、test、prod
spring:
  profiles:
    include: quartz,activiti,datasource
    active: dev
  cache:
    #配置 ehcache
    ehcache:
      #本地缓存名
      localname: localCache
      #配置文件路径
      config: ehcache/ehcache-config.xml

#####################################################################################################################################
# mybatis plus 主配置
#####################################################################################################################################
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
  mapper-locations: classpath*:mappers/mysql/*Mapper.xml
  global-config:
    #逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: N
      # 删除后
      logic-delete-value: Y


#####################################################################################################################################
# beetl 模版引擎
#####################################################################################################################################
beetl:
  enabled: true
  #模版路径
  templatesPath: /templates
  #配置文件路径
  configsPath: beetl/beetl.properties
  #后缀
  suffix: html


#####################################################################################################################################
# 拦截器 过滤器 路径配置
#####################################################################################################################################
application:
  interceptor:
    authorizationinterceptor:
      include: /**
      exclude: / , /kaptcha , /login , /static/**, css/**, js/**, img/**, json/**, fonts/**, *.html, *.json , *.js , *.json , *.css , *.png
  filter:
    loginfilter:
      include: /**
      exclude: /static/**, /druid/**
    charfilter:
      include: /**
      exclude: /static/**, /druid/**
    druidfilter:
      include: /**]
      exclude: /static/**, /druid/**
    paramfilter:
      include: /**
      exclude: /static/**, /druid/**

#####################################################################################################################################
# Shiro 权限控制 配置
#####################################################################################################################################
shiro:
  enabled: true
  # 使用hex算法还是bas64 ： true：hex false：base64
  isStoredCredentialsHexEncoded: false
  # 散列迭代次数
  hashiterations: 10
  # 散列算法，SHA-256 : 使用sha256算法  MD5 : 使用MD5算法 MD2 : 使用MD2算法  .. SHA-1 SHA-384 SHA-512
  hashalgorithmname: SHA-256
  loginUrl: /page/login
  successUrl: /page/index
  pathdefinitions:
    authc: /**
    anon: /kaptcha , /page/login , /login , /logout , /static/** , *.html, *.json , *.js , *.json , *.css , *.png